/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.lwk.avro.hello;

@SuppressWarnings("all")
/** i am an interface */
@org.apache.avro.specific.AvroGenerated
public interface HelloWorld {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"HelloWorld\",\"namespace\":\"com.lwk.avro.hello\",\"doc\":\"i am an interface\",\"types\":[{\"type\":\"record\",\"name\":\"Greeting\",\"doc\":\"i am a class\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"}]},{\"type\":\"error\",\"name\":\"Curse\",\"doc\":\"i am a exception class\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"}]}],\"messages\":{\"hello\":{\"doc\":\"i am a method\",\"request\":[{\"name\":\"greeting\",\"type\":\"Greeting\"}],\"response\":\"Greeting\",\"errors\":[\"Curse\"]}}}");
  /** i am a method */
  com.lwk.avro.hello.Greeting hello(com.lwk.avro.hello.Greeting greeting) throws org.apache.avro.AvroRemoteException, com.lwk.avro.hello.Curse;

  @SuppressWarnings("all")
  /** i am an interface */
  public interface Callback extends HelloWorld {
    public static final org.apache.avro.Protocol PROTOCOL = com.lwk.avro.hello.HelloWorld.PROTOCOL;
    /** i am a method */
    void hello(com.lwk.avro.hello.Greeting greeting, org.apache.avro.ipc.Callback<com.lwk.avro.hello.Greeting> callback) throws java.io.IOException;
  }
}